DROP TABLE IF EXISTS MEALLOG CASCADE;
DROP TABLE IF EXISTS RECIPE_INGREDIENT CASCADE;
DROP TABLE IF EXISTS INGREDIENT CASCADE;
DROP TABLE IF EXISTS FAVORITES CASCADE;
DROP TABLE IF EXISTS RECIPE CASCADE;
DROP TABLE IF EXISTS GOAL CASCADE;
DROP TABLE IF EXISTS "USER" CASCADE;